"""Initial Migration

Revision ID: 261f05f0cb78
Revises: 0dccd8efcce8
Create Date: 2022-03-14 18:11:33.501078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '261f05f0cb78'
down_revision = '0dccd8efcce8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('blog_id', sa.Integer(), nullable=True))
    op.drop_constraint('comment_owner_id_fkey', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'blogs', ['blog_id'], ['id'])
    op.drop_column('comment', 'owner_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_owner_id_fkey', 'comment', 'user', ['owner_id'], ['id'])
    op.drop_column('comment', 'blog_id')
    # ### end Alembic commands ###
